apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: next-me
  labels:
    app: account-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: account-service
          image: ghcr.io/sparta-next-me/account-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 11115 # account-service 포트

          envFrom:
            - secretRef:
                name: usergoal-env

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server.next-me.svc.cluster.local:3100"
            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
              value: "false" # 이 라인을 명시적으로 추가하세요!
            - name: SPRING_CLOUD_CONFIG_NAME
              value: "account-service"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx768m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 11115
            initialDelaySeconds: 80
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 11115
            initialDelaySeconds: 120
            periodSeconds: 20

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: next-me
spec:
  selector:
    app: account-service
  ports:
    - name: http
      port: 11115
      targetPort: 11115
  type: ClusterIP